# This docker compose file is used to deploy the "core"-services of a Crosslab instance.
# This includes all services to provide the crosslab API. Any additional software like frontend,
# virtual laboratory devices etc. must be deployed on top of this.
#
# All necessary confifguration Options are set via environment variables in the accompanying .env file.
#
x-config: &common-config
  AUTHORIZATION_SERVER: "http://authorization:3010"
  AUTHORIZATION_PSK: "${AUTHORIZATION_PSK:?}"
  LOGGING: "${LOGGING_LEVEL:-warn}"
  BASE_URL: ${API_BASE_URL}
  DB_TYPE: mariadb
  DB_HOST: db
  DB_PORT: 3306
  AUTH_SERVICE_URL: "http://auth:3000"
  DEVICE_SERVICE_URL: "http://device:3001"
  EXPERIMENT_SERVICE_URL: "http://experiment:3002"
  FEDERATION_SERVICE_URL: "http://federation:3003"
  FORWARDING_SERVICE_URL: "http://forwarding:3020"
  AUTH_SERVICE_DOMAIN: "auth:3000"
  DEVICE_SERVICE_DOMAIN: "device:3001"
  EXPERIMENT_SERVICE_DOMAIN: "experiment:3002"
  FEDERATION_SERVICE_DOMAIN: "federation:3003"
  AUTHORIZATION_SERVICE_DOMAIN: "authorization:3010"
  FORWARDING_SERVICE_DOMAIN: "forwarding:3020"

services:
  # =============== CROSSLAB SERVICES ===============
  db:
    image: mariadb:11.2.3
    volumes:
      - "./config/mariadb:/docker-entrypoint-initdb.d:ro"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?}
    networks:
      - service-network
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su=mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 5s
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.13.4
    volumes:
      - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    networks:
      - service-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
  gateway:
    image: gateway-service:latest
    environment:
      <<: *common-config
    networks:
      - service-network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  # Services
  auth:
    image: auth-service:latest
    environment:
      <<: *common-config
      DB_USERNAME: authentication
      DB_DATABASE: authentication
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?}
      JWT_SECRET: ${JWT_SECRET:?}
    networks:
      - service-network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  authorization:
    image: authorization-service:latest
    environment:
      <<: *common-config
      DB_USERNAME: authorization
      DB_DATABASE: authorization
      JWT_SECRET: ${JWT_SECRET:?}
    networks:
      - service-network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  device:
    image: device-service:latest
    environment:
      <<: *common-config
      DB_USERNAME: device
      DB_DATABASE: device
    networks:
      - service-network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  experiment:
    image: experiment-service:latest
    environment:
      <<: *common-config
      DB_USERNAME: experiment
      DB_DATABASE: experiment
    networks:
      - service-network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  federation:
    image: federation-service:latest
    environment:
      <<: *common-config
      DB_USERNAME: federation
      DB_DATABASE: federation
    networks:
      - service-network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  forwarding:
    image: forwarding-service:latest
    environment:
      <<: *common-config
      DB_USERNAME: forwarding
      DB_DATABASE: forwarding
    networks:
      - service-network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  # =============== NEW SERVICES ===============
  helper-gateway:
    image: helper-gateway:latest
    environment:
      - LOCAL_DOMAIN=localhost:${API_PORT:?}
      - DOCKER_DOMAIN=gateway:80
    ports:
      - ${API_PORT:?}:80
    depends_on:
      - gateway
    networks:
      - service-network
  compilation:
    image: arduino-cli-compilation-server:latest
    environment:
      - WEBSOCKET_ENDPOINT=http://gateway:80/devices/websocket
    networks:
      - service-network
    restart: on-failure
  editor:
    image: crosslab-editor:latest
    ports:
      - 3022:3022
    networks:
      - service-network
    restart: on-failure
networks:
  service-network:
    driver: bridge
