abstract-messaging-channel:
  path: code/shared/abstract-messaging-channel
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
    publish:
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - abstract-messaging-channel:build

crosslab-messaging-channel:
  path: code/shared/crosslab-messaging-channel
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - abstract-messaging-channel:publish
    publish:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - crosslab-messaging-channel:build

compilation-messaging-protocol:
  path: code/compilation/libraries/compilation-messaging-protocol
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - abstract-messaging-channel:publish
    publish:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - compilation-messaging-protocol:build

soa-client:
  path: code/shared/soa-client
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
    publish:
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - soa-client:build

crosslab-compilation-service:
  path: code/compilation/service
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - abstract-messaging-channel:publish
        - soa-client:publish
        - crosslab-messaging-channel:publish
        - compilation-messaging-protocol:publish
    publish:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - crosslab-compilation-service:build

arduino-cli-compilation-server:
  path: code/compilation/implementations/arduino-cli
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - soa-client:publish
        - crosslab-compilation-service:publish
    build-docker:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: docker build --network host -t arduino-cli-compilation-server .
      dependencies:
        - arduino-cli-compilation-server:build

crosslab-editor:
  path: code/editor
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
    build-docker:
      commands:
        execute: docker build --network host -t crosslab-editor .
      dependencies:
        - crosslab-editor:build