messaging-channels:
  path: code/shared/messaging-channels
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
    publish:
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - messaging-channels:build

crosslab-messaging-channel:
  path: code/shared/crosslab-messaging-channel
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - messaging-channels:publish
    publish:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - crosslab-messaging-channel:build

compilation-protocol:
  path: code/compilation/libraries/compilation-protocol
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - messaging-channels:publish
    publish:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - compilation-protocol:build

abstract-compilation-server:
  path: code/compilation/libraries/abstract-compilation-server
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - compilation-protocol:publish
        - messaging-channels:publish
    publish:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - abstract-compilation-server:build

crosslab-compilation-server:
  path: code/compilation/libraries/crosslab-compilation-server
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - messaging-channels:publish
        - compilation-protocol:publish
        - abstract-compilation-server:publish
    publish:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - crosslab-compilation-server:build

soa-client-js:
  path: code/shared/soa-client-js
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
    publish:
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - soa-client-js:build

crosslab-compilation-service:
  path: code/compilation/service
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - messaging-channels:publish
        - soa-client-js:publish
        - crosslab-messaging-channel:publish
        - compilation-protocol:publish
    publish:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: npm unpublish -f; npm publish
      dependencies:
        - crosslab-compilation-service:build

arduino-cli-compilation-server:
  path: code/compilation/implementations/arduino-cli
  jobs:
    build:
      commands:
        prepare: npm ci
        execute: npm run build
      dependencies:
        - soa-client-js:publish
        - crosslab-compilation-service:publish
    build-docker:
      helper-functions:
        before:
          - update-package-lock
        after:
          - revert-package-lock
      commands:
        execute: docker build --network host -t arduino-cli-compilation-server .
      dependencies:
        - arduino-cli-compilation-server:build