messaging-channels:
  path: code/shared/messaging-channels
  jobs:
    build:
      commands: 
        prepare: npm ci
        execute: npm run build

compilation-protocol:
  path: code/compilation/libraries/compilation-protocol
  jobs:
    build:
      prepare: npm ci
      commands: 
        prepare: npm ci
        execute: npm run build
      dependencies:
        - messaging-channels:build

abstract-compilation-server:
  path: code/compilation/libraries/abstract-compilation-server
  jobs:
    build:
      prepare: npm ci
      commands: 
        prepare: npm ci
        execute: npm run build
      dependencies:
        - compilation-protocol:build
        - messaging-channels:build

crosslab-compilation-server:
  path: code/compilation/libraries/crosslab-compilation-server
  jobs:
    build:
      prepare: npm ci
      commands: 
        prepare: npm ci
        execute: npm run build
      dependencies:
        - messaging-channels:build
        - compilation-protocol:build
        - abstract-compilation-server:build
